import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Dartivo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased bg-custom-black text-white font-sans initial-load`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Initialize CSS variables immediately when this script runs
              (function() {
                // Extract project ID from URL
                const pathSegments = window.location.pathname.split('/');
                const projectsIndex = pathSegments.indexOf('projects');
                const projectId = projectsIndex !== -1 && pathSegments[projectsIndex + 1]
                  ? pathSegments[projectsIndex + 1] : null;
                
                if (projectId) {
                  try {
                    // Load saved widths from localStorage
                    const rightSidebarKey = 'layout_' + projectId + '_rightSidebarWidth';
                    const phoneSidebarKey = 'layout_' + projectId + '_phoneSidebarWidth';
                    
                    const savedRightWidth = localStorage.getItem(rightSidebarKey);
                    const savedPhoneWidth = localStorage.getItem(phoneSidebarKey);
                    
                    if (savedRightWidth || savedPhoneWidth) {
                      const rightWidth = savedRightWidth ? JSON.parse(savedRightWidth) : 450;
                      const phoneWidth = savedPhoneWidth ? JSON.parse(savedPhoneWidth) : 400;
                      
                      // Set CSS variables immediately with high priority
                      document.documentElement.style.setProperty('--right-sidebar-width', rightWidth + 'px', 'important');
                      document.documentElement.style.setProperty('--phone-sidebar-width', phoneWidth + 'px', 'important');
                      
                      // Also inject inline styles for immediate application
                      const styleEl = document.createElement('style');
                      styleEl.innerHTML = ':root { --right-sidebar-width: ' + rightWidth + 'px !important; --phone-sidebar-width: ' + phoneWidth + 'px !important; }';
                      document.head.appendChild(styleEl);
                    }
                  } catch (error) {
                    console.error('Error loading sidebar widths:', error);
                  }
                }
              })();
            `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
